# Generated by Django 4.2.6 on 2023-11-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_college_created_at_college_updated_at_and_more'),
        ('professor', '0002_professorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.PositiveSmallIntegerField()),
                ('lesson_type', models.CharField(choices=[('0', 'General'), ('1', 'Specialized'), ('2', 'Basic')], max_length=1)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.college')),
                ('prerequisites', models.ManyToManyField(to='course.lesson')),
                ('requisites', models.ManyToManyField(to='course.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_day', models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday')], max_length=1)),
                ('class_start_time', models.CharField(max_length=128)),
                ('class_duration', models.FloatField()),
                ('class_location', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('exam_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.college')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professor.professorprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
