# Generated by Django 4.2.6 on 2023-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='requisites',
            field=models.ManyToManyField(blank=True, to='course.lesson'),
        ),
    ]
