# Generated by Django 4.2.6 on 2023-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lesson_prerequisites_alter_lesson_requisites'),
    ]

    def convert_char_to_time(apps, schema_editor):
        model = apps.get_model('course', 'course')
        try:
            model.objects.all().update(class_start_time="00:00:00")
        except:
            pass

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='exam_date',
            new_name='exam_specs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam_site',
        ),
        migrations.RunPython(convert_char_to_time),
        migrations.AlterField(
            model_name='course',
            name='class_start_time',
            field=models.TimeField(),
        ),
    ]
