# Generated by Django 4.2.6 on 2023-11-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_exam_date_course_exam_specs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='+', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='requisites',
            field=models.ManyToManyField(blank=True, related_name='+', to='course.lesson'),
        ),
    ]
