# Generated by Django 4.2.7 on 2023-11-13 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_lesson_prerequisites_alter_lesson_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_duration',
        ),
        migrations.AddField(
            model_name='course',
            name='class_finish_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
