# Generated by Django 4.2.7 on 2023-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_class_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_day',
            field=models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday')], max_length=1, verbose_name='Class Day'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_finish_time',
            field=models.TimeField(verbose_name='Class Finish Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Class Location'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_start_time',
            field=models.TimeField(verbose_name='Class Start Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_specs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exam Specifications'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('0', 'General'), ('1', 'Specialized'), ('2', 'Basic')], max_length=1, verbose_name='Lesson Type'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.PositiveSmallIntegerField(verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
