# Generated by Django 4.2.6 on 2023-11-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_college_created_at_college_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='include_valid_years',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
