# Generated by Django 4.2.7 on 2023-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_term_include_valid_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='college',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='field',
            name='educational_group',
            field=models.CharField(max_length=128, verbose_name='Educational Group'),
        ),
        migrations.AlterField(
            model_name='field',
            name='grade',
            field=models.CharField(max_length=1, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='field',
            name='units',
            field=models.PositiveSmallIntegerField(verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='term',
            name='class_finish',
            field=models.DateTimeField(verbose_name='Class Finish'),
        ),
        migrations.AlterField(
            model_name='term',
            name='class_start',
            field=models.DateTimeField(verbose_name='Class Start'),
        ),
        migrations.AlterField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='term',
            name='emergency_removal_finish',
            field=models.DateTimeField(verbose_name='Emergency Removal Finish'),
        ),
        migrations.AlterField(
            model_name='term',
            name='exams_start',
            field=models.DateTimeField(verbose_name='Exams Start'),
        ),
        migrations.AlterField(
            model_name='term',
            name='include_valid_years',
            field=models.BooleanField(verbose_name='Include Valid Years'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='term',
            name='selection_finish',
            field=models.DateTimeField(verbose_name='Selection Finish'),
        ),
        migrations.AlterField(
            model_name='term',
            name='selection_start',
            field=models.DateTimeField(verbose_name='Selection Start'),
        ),
        migrations.AlterField(
            model_name='term',
            name='substitution_finish',
            field=models.DateTimeField(verbose_name='Substitution Finish'),
        ),
        migrations.AlterField(
            model_name='term',
            name='substitution_start',
            field=models.DateTimeField(verbose_name='Substitution Start'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_finish',
            field=models.DateTimeField(verbose_name='Term Finish'),
        ),
        migrations.AlterField(
            model_name='term',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
