# Generated by Django 4.2.6 on 2023-11-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_exam_date_course_exam_specs_and_more'),
        ('course_selection', '0002_alter_studentcourse_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('registration', 'course')},
        ),
    ]
