# Generated by Django 4.2.6 on 2023-11-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0003_alter_studentcourse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseselectionrequest',
            name='valid_unit',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
    ]
