# Generated by Django 4.2.6 on 2023-11-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_created_at_studentprofile_updated_at_and_more'),
        ('course_selection', '0004_courseselectionrequest_valid_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseselectionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='student.studentprofile'),
        ),
    ]
