# Generated by Django 4.2.7 on 2023-11-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0005_alter_courseselectionrequest_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseselectionrequest',
            name='status',
            field=models.CharField(choices=[('0', 'StudentSubmit'), ('1', 'Deleted'), ('2', 'Pending'), ('3', 'Failed'), ('4', 'Professor Rejected'), ('5', 'Professor Valid')], max_length=1),
        ),
    ]
