# Generated by Django 4.2.6 on 2023-11-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(max_length=128, null=True)),
                ('order', models.CharField(max_length=128, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.college')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.field')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
